### ISSUE TITLE
no indication that you've annotated a page

### ISSUE THREAD

**Issue by alastair** [MTG/mtg-jamendo-annotator#5]
If you go to a page that you've previously annotated there should be a notification that you've annotated the items on this page.

Additionally, it could load the annotations for these sounds and fill in the radio boxes correctly

**Comment by xavierfav** [comment]
Now the user is warned when the page has already been annotated

However we do not fill the radio boxes with previous submitted annotations, so I leave this issue open.

**Comment by alastair** [comment]
Done in https://github.com/MTG/mtg-jamendo-annotator/commit/fc4818fb550758a2116ddcaee20480f581b513e6
